#-*- coding:utf-8 -*-

# 通用错误【1-100】
EC_LOGIN_INVALID = 1
ER_LOGIN_INVALID = "请先进行登录"


# 注册【101-200】
EC_REGISTER_PHONENUM_TYPE_ERROR = 101
ER_REGISTER_PHONENUM_TYPE_ERROR = '手机号格式错误，请重新输入'

EC_REGISTER_USERID_REPEAT = 102
ER_REGISTER_USERID_REPEAT = '该账号已被注册'

EC_REGISTER_IDCARD_TYPE_ERROR = 103
ER_REGISTER_IDCARD_TYPE_ERROR= '身份证格式错误，请重新输入'

EC_REGISTER_PASSWORD_TYPE_ERROR = 104
ER_REGISTER_PASSWORD_TYPE_ERROR= '密码格式错误，请重新输入'

# 登录【201-300】
EC_LOGIN_USERID_ERROR = 201
ER_LOGIN_USERID_ERROR = "账号不存在，请重新输入"
EC_LOGIN_PASSWORD_ERROR = 201
ER_LOGIN_PASSWORD_ERROR = "密码错误，请重新输入"

# 商城【301-400】
EC_SHOP_VERSION_LOW = 301
ER_SHOP_VERSION_LOW = "商城版本过低，请刷新重试"
EC_SHOP_BUY_LIST_NOT_EXIST = 302
ER_SHOP_BUY_LIST_NOT_EXIST = "该商品未上架"
EC_SHOP_BUY_PROP_NOT_EXIT = 303
ER_SHOP_BUY_PROP_NOT_EXIT = "该商品不存在"
EC_SHOP_BUY_CLIENT_VERSION_LOW = 304
ER_SHOP_BUY_CLIENT_VERSION_LOW = "客户端版本过低，请更新后重试"
EC_SHOP_BUY_INVENIORY_NOT_ENOUGH = 305
ER_SHOP_BUY_INVENIORY_NOT_ENOUGH = "商品库存不足"
EC_SHOP_BUY_MONEY_NOT_ENOUGH = 306
ER_SHOP_BUY_MONEY_NOT_ENOUGH = "游戏币不足，请充值后在购买"
EC_SHOP_BUY_COIN_NOT_ENOUGH = 307
ER_SHOP_BUY_COIN_NOT_ENOUGH = "充值币不足，请充值后在购买"


# 任务【401-500】
EC_TASK_ID_INVALID = 401
ER_TASK_ID_INVALID = "任务ID不合法"
EC_TASK_NOT_FINISTH = 402
ER_TASK_NOT_FINISTH = "用户未完成任务"
EC_TASK_SIGN_TYPE_ERROR = 403
ER_TASK_SIGN_TYPE_ERROR = "签到类型错误"